"""Initial migration

Revision ID: 1da8b093fe11
Revises: 
Create Date: 2025-02-20 10:30:17.889125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da8b093fe11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranking', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
