"""Added distillery, proof, and age to Bourbon model

Revision ID: 33611aa25b9e
Revises: 3fa4071ba976
Create Date: 2025-02-20 15:22:28.278171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33611aa25b9e'
down_revision = '3fa4071ba976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bourbon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_bourbon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('distillery', sa.VARCHAR(length=100), nullable=False),
    sa.Column('proof', sa.FLOAT(), nullable=False),
    sa.Column('age', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
