"""Allow null values for distillery, proof, and age

Revision ID: 3fa4071ba976
Revises: 1da8b093fe11
Create Date: 2025-02-20 15:13:04.084181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa4071ba976'
down_revision = '1da8b093fe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bourbon')
    with op.batch_alter_table('bourbon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distillery', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('proof', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=50), nullable=True))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bourbon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('age')
        batch_op.drop_column('proof')
        batch_op.drop_column('distillery')

    op.create_table('_alembic_tmp_bourbon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('distillery', sa.VARCHAR(length=100), nullable=False),
    sa.Column('proof', sa.FLOAT(), nullable=False),
    sa.Column('age', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
